#!/bin/bash
"""
🚀 Three.js Evolution Registry - 一键部署脚本

Usage:
    chmod +x deploy.sh
    ./deploy.sh
"""

set -e

echo "🦞 OpenClaw Evolution Registry - 部署脚本"
echo "============================================"
echo ""

# 检查 Git 配置
if ! git config user.email &>/dev/null; then
    echo "📝 配置 Git 用户信息..."
    git config user.email "openclaw@example.com"
    git config user.name "OpenClaw Bot"
fi

# 检查是否在正确的目录
if [ ! -f "index.html" ]; then
    echo "❌ 错误: 找不到 index.html，请确保在正确的目录运行"
    exit 1
fi

# 读取 GitHub 用户名
read -p "👤 请输入你的 GitHub 用户名: " GITHUB_USER

if [ -z "$GITHUB_USER" ]; then
    echo "❌ 错误: 用户名不能为空"
    exit 1
fi

echo ""
echo "🔧 准备部署..."
echo "📦 用户名: $GITHUB_USER"
echo ""

# 1. 初始化/更新 Git
echo "📝 初始化 Git 仓库..."
if [ ! -d ".git" ]; then
    git init -q
    git config user.email "openclaw@example.com"
    git config user.name "OpenClaw Bot"
fi

# 2. 添加所有文件
echo "📦 添加文件到 Git..."
git add -A

# 3. 提交
echo "💾 创建提交..."
COMMIT_MSG=$(cat <<EOF
🦞 OpenClaw Evolution Registry - $(date +%Y-%m-%d)

🎯 功能:
- Three.js 基础基因
- 进化追踪系统
- GitHub Pages 自动部署
- 现代化 Web UI

🤖 Auto-generated by OpenClaw
EOF
)
git commit -q -m "$COMMIT_MSG"

# 4. 重命名分支
echo "🔀 重命名分支为 main..."
git branch -M main 2>/dev/null || true

# 5. 创建 GitHub 仓库
echo ""
echo "📦 创建 GitHub 仓库..."
gh repo create ThreeJSEvolution \
    --public \
    --description "OpenClaw Evolution Registry - Three.js 能力进化系统 🦞🧬" \
    --source=. \
    --push 2>/dev/null

if [ $? -ne 0 ]; then
    echo ""
    echo "⚠️ GitHub CLI 不可用，将使用 SSH 方式..."
    echo ""
    echo "📝 请手动执行以下步骤："
    echo ""
    echo "1️⃣  访问 https://github.com/new 创建名为 'ThreeJSEvolution' 的仓库"
    echo ""
    echo "2️⃣  运行以下命令："
    echo ""
    cat << 'CMDS'
git remote add origin git@github.com:USERNAME/ThreeJSEvolution.git
git push -u origin main
CMDS
    echo ""
    echo "3️⃣  启用 GitHub Pages:"
    echo "   - 进入仓库 Settings → Pages"
    echo "   - Source 选择 'Deploy from a branch'"
    echo "   - Branch 选择 'main' /(root)"
    echo "   - 点击 Save"
    echo ""
    exit 0
fi

echo ""
echo "✅ 部署完成！"
echo ""
echo "🎉 下一步:"
echo ""
echo "1️⃣  启用 GitHub Pages:"
echo "   访问 https://github.com/$GITHUB_USER/ThreeJSEvolution/settings/pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo "   - 点击 Save"
echo ""
echo "2️⃣  访问你的网站:"
echo "   https://$GITHUB_USER.github.io/ThreeJSEvolution/"
echo ""
echo "3️⃣  验证部署:"
echo "   - 打开上面的链接"
echo "   - 应该能看到 OpenClaw Evolution 主页"
echo "   - 点击 '立即体验' 测试 Three.js 演示"
echo ""
echo "📊 GitHub 仓库:"
echo "   https://github.com/$GITHUB_USER/ThreeJSEvolution"
echo ""
echo "🧬 持续更新:"
echo "   - 每次 push 到 main 分支会自动部署"
echo "   - 访问上面的链接查看最新版本"
echo ""
